/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form.concert;

import domain.Band;
import domain.Concert;
import domain.Song;
import domain.SongPerformance;
import domain.Stage;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import transfer.Response;
import view.form.componenet.table.SetlistTableModel;
import controller.Controller;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author VeljkoBlagojevic
 */
public class FormInsertConcert extends javax.swing.JDialog {

    private Concert concert;

    /**
     * Creates new form FormInsertConcert
     */
    public FormInsertConcert(java.awt.Frame parent, boolean modal) {
        initComponents();
        concert = new Concert();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConcert = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblBand = new javax.swing.JLabel();
        lblStage = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        cmbBand = new javax.swing.JComboBox();
        cmbStage = new javax.swing.JComboBox();
        pnlSetlist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbOriginalSong = new javax.swing.JComboBox();
        txtLength = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSetlist = new javax.swing.JTable();
        btnAddToSetlist = new javax.swing.JButton();
        btnRemoveSong = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        pnlConcert.setBorder(javax.swing.BorderFactory.createTitledBorder("Concert"));

        lblID.setText("ID:");

        lblStartTime.setText("Start time:");

        lblBand.setText("Band:");

        lblStage.setText("Stage:");

        txtID.setEnabled(false);

        pnlSetlist.setBorder(javax.swing.BorderFactory.createTitledBorder("Setlist"));

        jLabel1.setText("Original song:");

        jLabel2.setText("Length:");

        tblSetlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSetlist);

        btnAddToSetlist.setText("Add to setlist");
        btnAddToSetlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToSetlistActionPerformed(evt);
            }
        });

        btnRemoveSong.setText("Remove from setlist");
        btnRemoveSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSetlistLayout = new javax.swing.GroupLayout(pnlSetlist);
        pnlSetlist.setLayout(pnlSetlistLayout);
        pnlSetlistLayout.setHorizontalGroup(
            pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(pnlSetlistLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSetlistLayout.createSequentialGroup()
                        .addComponent(btnAddToSetlist, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtLength)
                    .addComponent(cmbOriginalSong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        pnlSetlistLayout.setVerticalGroup(
            pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetlistLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbOriginalSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToSetlist)
                    .addComponent(btnRemoveSong))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlConcertLayout = new javax.swing.GroupLayout(pnlConcert);
        pnlConcert.setLayout(pnlConcertLayout);
        pnlConcertLayout.setHorizontalGroup(
            pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcertLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartTime)
                    .addComponent(lblBand)
                    .addComponent(lblID)
                    .addComponent(lblStage))
                .addGap(61, 61, 61)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtStartTime)
                    .addComponent(cmbBand, 0, 256, Short.MAX_VALUE)
                    .addComponent(cmbStage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlConcertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSetlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlConcertLayout.setVerticalGroup(
            pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcertLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartTime)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBand)
                    .addComponent(cmbBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStage)
                    .addComponent(cmbStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlSetlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlConcert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConcert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddToSetlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToSetlistActionPerformed
        try {
            Song originalSong = (Song) cmbOriginalSong.getSelectedItem();
            Integer length = Integer.valueOf(txtLength.getText().trim());
            SongPerformance songPerformance = new SongPerformance(length, originalSong, concert);
            ((SetlistTableModel) tblSetlist.getModel()).addSongPerformance(songPerformance);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Make sure to input valid arguments\n" + ex.getMessage(), "Parse Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddToSetlistActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (Objects.isNull(concert)) {
            concert = new Concert();
        }

        try {
            updateConcertInfo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Make sure to input valid arguments\n" + ex.getMessage(), "Parse Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        final int selectedOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to save " + this.concert + "!?", "Save", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (selectedOption != JOptionPane.OK_OPTION) {
            return;
        }

        try {
            Response response = Controller.getInstance().saveConcert(this.concert);

            if (response.getException() == null) {
                this.concert = (Concert) response.getResult();
                updateConcertFormInfo();
                JOptionPane.showMessageDialog(this, "Stage " + this.concert + " is succesuflly saved!", "Success!", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "System could not save the concert\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not save the concert\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRemoveSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSongActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = tblSetlist.getSelectedRows();
        System.out.println("selected rows: " + Arrays.stream(selectedRows)
                .mapToObj(selectedRow -> String.valueOf(selectedRow))
                .collect(Collectors.joining(", ")));

        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "You must select columns to delete from table", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (selectedRows.length > 1) {
            JOptionPane.showMessageDialog(this, "You can only delete one item at the  time", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Arrays.stream(selectedRows).forEach(selectedRow -> {
            ((SetlistTableModel) tblSetlist.getModel()).removeAt(selectedRow);
            //            concert.getSetlist().remove(selectedRow);
            ((SetlistTableModel) tblSetlist.getModel()).setSetlist(concert.getSetlist());
        });
    }//GEN-LAST:event_btnRemoveSongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToSetlist;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemoveSong;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbBand;
    private javax.swing.JComboBox cmbOriginalSong;
    private javax.swing.JComboBox cmbStage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBand;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblStage;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JPanel pnlConcert;
    private javax.swing.JPanel pnlSetlist;
    private javax.swing.JTable tblSetlist;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        prepareBandsCombobox();
        prepareStagesCombobox();
        prepareSongsCombobox();
        prepareSetlistTable();
    }

    private List<Song> getAllSongs() {
        try {
            Response response = Controller.getInstance().getAllSongs();
            if (response.getException() == null) {
                var songs = (List<Song>) response.getResult();
                if (songs.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "System could not find songs\n", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "System has found songs\n", "Found songs", JOptionPane.INFORMATION_MESSAGE);
                }
                return songs;
            } else {
                JOptionPane.showMessageDialog(this, "System could not find concerts\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            return Collections.EMPTY_LIST;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not find concerts\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return Collections.EMPTY_LIST;
        }
    }

    private List<Band> getAllBands() {
        try {
            Response response = Controller.getInstance().getAllBands();
            if (response.getException() == null) {
                var bands = (List<Band>) response.getResult();
                if (bands.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "System could not found bands\n", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "System has found bands\n", "Found bands", JOptionPane.INFORMATION_MESSAGE);
                }
                return bands;
            } else {
                JOptionPane.showMessageDialog(this, "System could not find bands\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return Collections.EMPTY_LIST;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not find bands\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return Collections.EMPTY_LIST;

        }
    }

    private List<Stage> getAllStages() {
        try {
            Response response = Controller.getInstance().getAllStages();
            if (response.getException() == null) {
                var stages = (List<Stage>) response.getResult();
                if (stages.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "System could not find stages", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "System has found stages", "Found stages", JOptionPane.INFORMATION_MESSAGE);
                }
                return stages;
            } else {
                JOptionPane.showMessageDialog(this, "System could not find stages\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return Collections.EMPTY_LIST;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not find stages\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return Collections.EMPTY_LIST;

        }
    }

    private void prepareBandsCombobox() {
        List<Band> bands = getAllBands();
        cmbBand.setModel(new DefaultComboBoxModel<>(bands.toArray()));
    }

    private void prepareStagesCombobox() {
        List<Stage> stages = getAllStages();
        cmbStage.setModel(new DefaultComboBoxModel<>(stages.toArray()));
    }

    private void prepareSongsCombobox() {
        List<Song> songs = getAllSongs();
        cmbOriginalSong.setModel(new DefaultComboBoxModel<>(songs.toArray()));
    }

    private void prepareSetlistTable() {
        tblSetlist.setModel(new SetlistTableModel(new ArrayList<>()));
    }

    private void updateConcertInfo() throws Exception {
        if (Objects.nonNull(concert) && Objects.nonNull(concert.getId())) {
            concert.setId(Long.valueOf(txtID.getText()));
        }
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date starttime = dateFormat.parse(txtStartTime.getText().trim());
            concert.setStartTime(starttime);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Insert proper format for date\n" + ex.getMessage(), "Parse Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

        concert.setBand((Band) cmbBand.getSelectedItem());
        concert.setStage((Stage) cmbStage.getSelectedItem());
        concert.setSetlist(((SetlistTableModel) tblSetlist.getModel()).getSetlist());
    }

    private void updateConcertFormInfo() {
        if (Objects.isNull(concert)) {
            return;
        }
        txtID.setText(String.valueOf(concert.getId()));
        txtStartTime.setText(new SimpleDateFormat("yyy-MM-dd").format(concert.getStartTime()));
        cmbBand.setSelectedItem(concert.getBand());
        cmbStage.setSelectedItem(concert.getStage());
        tblSetlist.setModel(new SetlistTableModel(concert.getSetlist()));
    }
}
