/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import domain.User;
import java.util.List;
import form.component.table.UserTableModel;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import server.Server;
import thread.ProcessClientRequests;

/**
 *
 * @author LENOVO
 */
public class FrmActiveUsers extends javax.swing.JDialog {

    /**
     * Creates new form FrmActiveUsers
     */
    public FrmActiveUsers(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        prepareView();
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                try {
                    fillTable();
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        }, 1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User", "Login time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

//    private void prepareView() {
//        tbl.setModel(new UserTableModel(users));
//    }

    private void fillTable() {
        List<ProcessClientRequests> clients = Server.loggedClients;
        DefaultTableModel dtm = (DefaultTableModel) this.tbl.getModel();
        int rows = dtm.getRowCount();
        if (rows >= 0) {
            for (int i = rows - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
        }

        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        for (ProcessClientRequests ch : clients) {
            if (ch.getUser() != null) {
                String loginTime = sdf.format(ch.getLoginTime());
                dtm.addRow(new Object[]{ch.getUser().toString(), loginTime});
            }
        }
    }
}
