package view.form.stage;

import controller.Controller;
import domain.Stage;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import transfer.Response;
import view.form.componenet.table.StageTableModel;

/**
 *
 * @author VeljkoBlagojevic
 */
public class FormViewStages extends javax.swing.JFrame {

    private TableModel model;

    /**
     * Creates new form FormViewStages
     */
    public FormViewStages() {
        initComponents();
        fillTableStages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStages = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(tblStages);

        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilterKeyTyped(evt);
            }
        });

        jLabel1.setText("Search stages by name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(480, 480, 480)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        final int selectedItemsCount = tblStages.getSelectionModel().getSelectedItemsCount();
        if (selectedItemsCount == 0) {
            JOptionPane.showMessageDialog(this, "You have not selected stage you want to see details for!", "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (selectedItemsCount > 1) {
            JOptionPane.showMessageDialog(this, "You have selected multiple stages. Please select only one stage you want to see details for!", "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int selectedRow = tblStages.getSelectionModel().getSelectedIndices()[0];
        Stage stage = ((StageTableModel) tblStages.getModel()).getStageAt(selectedRow);
        new FormStage(this, false, stage).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void txtFilterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyTyped
//        final TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
//        tblStages.setRowSorter(sorter);
//
//        String text = txtFilter.getText();
//        if (text.length() == 0) {
//            sorter.setRowFilter(null);
//        } else {
//            try {
//                sorter.setRowFilter(RowFilter.regexFilter(text));
//            } catch (PatternSyntaxException pse) {
//                System.out.println("Bad regex pattern");
//            }
//        }

        String filteringCriteria = txtFilter.getText();

        Stage searchStageParam = new Stage();
        searchStageParam.setName(filteringCriteria);

        try {
            Response response = Controller.getInstance().getAllStagesFiltered(searchStageParam);

            if (response.getException() == null) {
                List<Stage> stages = (List<Stage>) response.getResult();
                if (stages.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "System could not find stages with search criteria\n", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "System has found stages with search criteria\n", "Found stages", JOptionPane.INFORMATION_MESSAGE);
                }
                model = new StageTableModel(stages);
                tblStages.setModel(model);
            } else {
                JOptionPane.showMessageDialog(this, "System could not find stages with search criteria\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not find stages with search criteria\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtFilterKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStages;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    public void fillTableStages() {
        try {
            Response response = Controller.getInstance().getAllStages();
            if (response.getException() == null) {
                List<Stage> stages = (List<Stage>) response.getResult();
                if (stages.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "System could not find stages\n", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "System has found stages\n", "Found stages", JOptionPane.INFORMATION_MESSAGE);
                }
                model = new StageTableModel(stages);
                tblStages.setModel(model);
            } else {
                JOptionPane.showMessageDialog(this, "System could not find stages\n" + response.getException().getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "System could not find stages\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
