package operation;

/**
 *
 * @author VeljkoBlagojevic
 */
public enum Operation {
    LOGIN, REGISTER, LOGOUT,
    SAVE_STAGE, GET_ALL_STAGES, UPDATE_STAGE, DELETE_STAGE, GET_ALL_STAGES_FILTERED,
    SAVE_BAND, GET_ALL_BANDS, UPDATE_BAND, DELETE_BAND, GET_ALL_BANDS_FILTERED,
    SAVE_SONG, GET_ALL_SONGS, UPDATE_SONG, DELETE_SONG, GET_ALL_SONGS_BY_BAND, GET_ALL_SONGS_FILTERED,
    SAVE_CONCERT, GET_ALL_CONCERTS, UPDATE_CONCERT, DELETE_CONCERT, FIND_CONCERT_BY_ID, GET_ALL_CONCERTS_FILTERED;
}
